//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class M_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "95706d2d-d3ac-4e84-ad39-6cafcefbf2e9:DoNotCallOverridableMethodsInConstructors")]
        public M_Category()
        {
           this.M_Product = new HashSet<M_Product>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid CompanyId { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }

        [ForeignKey("CompanyId")]
        public virtual M_Company M_Company { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "a7db10a4-ebd7-4b6a-95af-d22811454840:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Product> M_Product { get; set; }
    }
}
