//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BE.Core
{
    public partial class M_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "b8faa3c6-f548-4aa2-8493-959227ac53a9:DoNotCallOverridableMethodsInConstructors")]
        public M_Company()
        {
           this.M_Branch = new HashSet<M_Branch>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "ef3d8d7e-fc7d-4ad6-b5b7-f08447ed965d:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Branch> M_Branch { get; set; }
    }
}
