//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class M_ExpenseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "62041546-1ed2-4bc9-949e-f01f55c4af2f:DoNotCallOverridableMethodsInConstructors")]
        public M_ExpenseType()
        {
           this.T_Expense = new HashSet<T_Expense>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "7b893f78-5acb-48a7-9114-1a1554e96384:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Expense> T_Expense { get; set; }
    }
}
