//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class M_ItemsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "82feb89f-74a3-44bd-8360-4a8c87b29ad9:DoNotCallOverridableMethodsInConstructors")]
        public M_ItemsType()
        {
           this.M_Items = new HashSet<M_Items>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "388e2551-97a4-4b16-9e93-4a10352dcb42:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Items> M_Items { get; set; }
    }
}
