//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class M_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "e03419b7-04b7-4bfc-b420-c858e5b01490:DoNotCallOverridableMethodsInConstructors")]
        public M_Items()
        {
           this.T_PurchaseOrderDetails = new HashSet<T_PurchaseOrderDetails>();
           this.T_SalesOrderDetails = new HashSet<T_SalesOrderDetails>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid ItemsTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }

        [ForeignKey("ItemsTypeId")]
        public virtual M_ItemsType M_ItemsType { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "fbfe8133-dd6b-4dbc-904c-bf4a90198c6e:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PurchaseOrderDetails> T_PurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "fbfe8133-dd6b-4dbc-904c-bf4a90198c6e:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SalesOrderDetails> T_SalesOrderDetails { get; set; }
    }
}
