//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class M_ItemsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "d48d277c-e1e2-4a72-8df9-bcc09eedddd7:DoNotCallOverridableMethodsInConstructors")]
        public M_ItemsType()
        {
           this.M_Items = new HashSet<M_Items>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "f91c7048-4f11-499d-83ef-6aacddc6b2bb:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Items> M_Items { get; set; }
    }
}
