//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class T_Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "e6e97224-bcb8-4c83-92e4-1163b90c5aba:DoNotCallOverridableMethodsInConstructors")]
        public T_Loan()
        {
           this.T_LoanDetails = new HashSet<T_LoanDetails>();
        }

        [Key]
        public Guid Id { get; set; }
        public System.DateTime EventDate { get; set; }
        public string LoanNumber { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "bb6aa063-ea81-449f-a6a4-10a97aa632b3:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LoanDetails> T_LoanDetails { get; set; }
    }
}
