//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class T_OutStanding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "3cba7712-2713-42a1-beb4-18d03030b147:DoNotCallOverridableMethodsInConstructors")]
        public T_OutStanding()
        {
           this.T_OutStandingDetails = new HashSet<T_OutStandingDetails>();
        }

        [Key]
        public Guid Id { get; set; }
        public System.DateTime EventDate { get; set; }
        public string OSNumber { get; set; }
        public Nullable<Guid> SalesOrderId { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }

        [ForeignKey("SalesOrderId")]
        public virtual T_SalesOrder T_SalesOrder { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "b55875aa-68e4-4ac9-881c-466f0049be79:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OutStandingDetails> T_OutStandingDetails { get; set; }
    }
}
