//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class T_PurchaseOrderDetails
    {
        [Key]
        public Guid Id { get; set; }
        public Guid PurchaseOrderId { get; set; }
        public int SlNo { get; set; }
        public Guid ItemsId { get; set; }
        public Guid BrandId { get; set; }
        public Guid GuageId { get; set; }
        public Guid UomId { get; set; }
        public decimal Quantity { get; set; }
        public decimal BuyingRate { get; set; }
        public decimal BuyingPrice { get; set; }
        public decimal SellingRate { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal DifferenceAmount { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }

        [ForeignKey("BrandId")]
        public virtual M_Brand M_Brand { get; set; }
        [ForeignKey("GuageId")]
        public virtual M_Guage M_Guage { get; set; }
        [ForeignKey("ItemsId")]
        public virtual M_Items M_Items { get; set; }
        [ForeignKey("UomId")]
        public virtual M_UOM M_UOM { get; set; }
        [ForeignKey("PurchaseOrderId")]
        public virtual T_PurchaseOrder T_PurchaseOrder { get; set; }
    }
}
