//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class T_PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "f37aeecd-4b1e-41bd-b3ca-98b4cf7cfa13:DoNotCallOverridableMethodsInConstructors")]
        public T_PurchaseOrder()
        {
           this.T_PurchaseOrderDetails = new HashSet<T_PurchaseOrderDetails>();
        }

        [Key]
        public Guid Id { get; set; }
        public string OrderId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string BillerName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "4939f05f-eb61-4747-b73b-480624bd6dec:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PurchaseOrderDetails> T_PurchaseOrderDetails { get; set; }
    }
}
