//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class T_PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "8c3c99e6-3646-459f-99a6-0d41c25bbf7b:DoNotCallOverridableMethodsInConstructors")]
        public T_PurchaseOrder()
        {
           this.T_PurchaseOrderDetails = new HashSet<T_PurchaseOrderDetails>();
        }

        [Key]
        public Guid Id { get; set; }
        public string OrderId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string BillerName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "fecd5773-65fa-46a6-81c9-dea17bdd80dd:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PurchaseOrderDetails> T_PurchaseOrderDetails { get; set; }
    }
}
