//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    public partial class T_PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "598afda6-1b6a-4e7b-8fa1-3e8821289765:DoNotCallOverridableMethodsInConstructors")]
        public T_PurchaseOrder()
        {
           this.T_PurchaseOrderDetails = new HashSet<T_PurchaseOrderDetails>();
        }

        [Key]
        public Guid Id { get; set; }
        public string OrderId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string BillerName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "10f34ec6-3fe9-450c-800c-b428ed9b7477:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PurchaseOrderDetails> T_PurchaseOrderDetails { get; set; }
    }
}
