//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BE.Core
{
    [MetadataType(typeof(Menu_Categories_MetaData))]
    public partial class Menu_Categories
    {
    }

    public class Menu_Categories_MetaData
    {
        [Display(Name= "Id")]
        [Required(ErrorMessage = "{0} is required")]
        public int Id { get; set; }

        [Display(Name= "CategoryName")]
        public string CategoryName { get; set; }

        [Display(Name= "ParentCategoryId")]
        public Nullable<int> ParentCategoryId { get; set; }

        [Display(Name= "Remarks")]
        public string Remarks { get; set; }

    }
}
