//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    [MetadataType(typeof(T_PurchaseOrderDetails_MetaData))]
    public partial class T_PurchaseOrderDetails
    {
        [NotMapped]
        public string ItemsName { get; set; }
        [NotMapped]
        public string CategoryName { get; set; }
        [NotMapped]
        public string GuageName { get; set; }
        [NotMapped]
        public string UomName { get; set; }
    }

    public class T_PurchaseOrderDetails_MetaData
    {
        [Display(Name= "Id")]
        [Required(ErrorMessage = "{0} is required")]
        public Guid Id { get; set; }

        [Display(Name= "PurchaseOrderId")]
        [Required(ErrorMessage = "{0} is required")]
        public Guid PurchaseOrderId { get; set; }

        [Display(Name= "SlNo")]
        [Required(ErrorMessage = "{0} is required")]
        public int SlNo { get; set; }

        [Display(Name= "ProductId")]
        [Required(ErrorMessage = "{0} is required")]
        public Guid ProductId { get; set; }

        [Display(Name= "UomId")]
        [Required(ErrorMessage = "{0} is required")]
        public Guid UomId { get; set; }

        [Display(Name= "Quantity")]
        [Required(ErrorMessage = "{0} is required")]
        public decimal Quantity { get; set; }

        [Display(Name= "BuyingRate")]
        [Required(ErrorMessage = "{0} is required")]
        public decimal BuyingRate { get; set; }

        [Display(Name= "BuyingPrice")]
        [Required(ErrorMessage = "{0} is required")]
        public decimal BuyingPrice { get; set; }

        [Display(Name= "SellingRate")]
        [Required(ErrorMessage = "{0} is required")]
        public decimal SellingRate { get; set; }

        [Display(Name= "SellingPrice")]
        [Required(ErrorMessage = "{0} is required")]
        public decimal SellingPrice { get; set; }

        [Display(Name= "DifferenceAmount")]
        [Required(ErrorMessage = "{0} is required")]
        public decimal DifferenceAmount { get; set; }

        [Display(Name= "Remark")]
        public string Remark { get; set; }

        [Display(Name= "CreatedBy")]
        public string CreatedBy { get; set; }

        [Display(Name= "CreatedDate")]
        [Required(ErrorMessage = "{0} is required")]
        public System.DateTime CreatedDate { get; set; }

        [Display(Name= "ModifyBy")]
        public string ModifyBy { get; set; }

        [Display(Name= "ModifyDate")]
        public Nullable<System.DateTime> ModifyDate { get; set; }

    }
}
