//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BE.Core
{
    [MetadataType(typeof(T_SalesOrderDetails_MetaData))]
    public partial class T_SalesOrderDetails
    {
        [NotMapped]
        public string ItemsName { get; set; }
        [NotMapped]
        public string ItemsTypeName { get; set; }
        [NotMapped]
        public string UomName { get; set; }
    }

    public class T_SalesOrderDetails_MetaData
    {
        [Display(Name= "Id")]
        [Required(ErrorMessage = "{0} is required")]
        public Guid Id { get; set; }

        [Display(Name= "SalesOrderId")]
        [Required(ErrorMessage = "{0} is required")]
        public Guid SalesOrderId { get; set; }

        [Display(Name= "SlNo")]
        [Required(ErrorMessage = "{0} is required")]
        public int SlNo { get; set; }

        [Display(Name= "ItemsId")]
        [Required(ErrorMessage = "{0} is required")]
        public Guid ItemsId { get; set; }

        [Display(Name= "UomId")]
        [Required(ErrorMessage = "{0} is required")]
        public Guid UomId { get; set; }

        [Display(Name= "StockQuantity")]
        [Required(ErrorMessage = "{0} is required")]
        public decimal StockQuantity { get; set; }

        [Display(Name= "Quantity")]
        [Required(ErrorMessage = "{0} is required")]
        public decimal Quantity { get; set; }

        [Display(Name= "LatestPrice")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayFormat(DataFormatString = "{0:#.##}", ApplyFormatInEditMode = true)]
        public decimal LatestPrice { get; set; }

        [Display(Name= "SellingPrice")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayFormat(DataFormatString = "{0:#.##}", ApplyFormatInEditMode = true)]
        public decimal SellingPrice { get; set; }

        [Display(Name= "CreatedBy")]
        public string CreatedBy { get; set; }

        [Display(Name= "CreatedDate")]
        [Required(ErrorMessage = "{0} is required")]
        public System.DateTime CreatedDate { get; set; }

        [Display(Name= "ModifyBy")]
        public string ModifyBy { get; set; }

        [Display(Name= "ModifyDate")]
        public Nullable<System.DateTime> ModifyDate { get; set; }

    }
}
