//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using BE.Core;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace BE.Services.DbConnections
{
    public partial class SqlDbContext : DbContext
    {
        public SqlDbContext() : base(SqlDbConnection.ConString)
        {
            Database.SetInitializer<SqlDbContext>(null);
            //SqlDbConnection.ConString
            //name=OsConnectionEntities
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);
        }

        public virtual DbSet<M_Branch> M_Branch{ get; set; }
        public virtual DbSet<M_Brand> M_Brand{ get; set; }
        public virtual DbSet<M_Company> M_Company{ get; set; }
        public virtual DbSet<M_Guage> M_Guage{ get; set; }
        public virtual DbSet<M_Product> M_Product{ get; set; }
        public virtual DbSet<M_ProductType> M_ProductType{ get; set; }
        public virtual DbSet<M_Supplier> M_Supplier{ get; set; }
        public virtual DbSet<M_UOM> M_UOM{ get; set; }
        public virtual DbSet<M_User> M_User{ get; set; }
    }
}
