//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace BE.Services.SqlDbConnections
{
    public partial class SqlDbContext : DbContext
    {
        public SqlDbContext() : base(SqlSqlDbConnection.ConString)
        {
            Database.SetInitializer<SqlDbContext>(null);
            //SqlDbConnection.ConString
            //name=BEnterprisesConnectionEntities
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);
        }

    }
}
