//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using BE.Services.Repository;
using BE.Core;

namespace BE.Services.UnitOfWork
{
    public interface IUnitOfWork
    {
        void Save();

        IGenericRepository<Menu_Categories> Menu_Categories_Repository { get; set; }
    }
}
