//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using BE.Services.Repository;
using BE.Services.DbConnections;
using BE.Core;

namespace BE.Services.UnitOfWork
{
    public partial class UnitOfWork : IUnitOfWork, System.IDisposable
    {
        private readonly SqlDbContext _context;
        private bool disposed;

        public UnitOfWork()
        {
            this._context = new SqlDbContext();
        }
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
        public void Save()
        {
            _context.SaveChanges();
        }
        public virtual void Dispose(bool disposing)
        {
            if (!disposed)
            {
                if (disposing)
                {
                    _context.Dispose();
                }
            }
            disposed = true;
        }


        public IGenericRepository<Menu_Categories> Menu_Categories_Repository { get; set; }
        public IGenericRepository<Menu_Categories> _Menu_Categories_Repository
        {
            get { return Menu_Categories_Repository ?? (Menu_Categories_Repository= new GenericRepository<Menu_Categories>(_context)); }
            set { _Menu_Categories_Repository = value; }
        }
    }
}
