//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using BE.Services.RepBEnterprisesitory;
using BE.Services.SqlDbConnections;

namespace BE.Services.UnitOfWork
{
    public partial class UnitOfWork : IUnitOfWork, System.IDispBEnterprisesable
    {
        private readonly SqlDbContext _context;
        private bool dispBEnterprisesed;

        public UnitOfWork()
        {
            this._context = new SqlDbContext();
        }
        public void DispBEnterprisese()
        {
            DispBEnterprisese(true);
            GC.SuppressFinalize(this);
        }
        public void Save()
        {
            _context.SaveChanges();
        }
        public virtual void DispBEnterprisese(bool dispBEnterprisesing)
        {
            if (!dispBEnterprisesed)
            {
                if (dispBEnterprisesing)
                {
                    _context.DispBEnterprisese();
                }
            }
            dispBEnterprisesed = true;
        }


    }
}
